config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users
  resources :users do
    delete :delete_profile_picture
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :profile_picture

    validates :first_name, presence: true
    validates :last_name, presence: true
    # validates :profile_picture, presence: true
    validate :validate_profile_picture_format

    private

    def validate_profile_picture_format
        return unless profile_picture.attached?
    
        unless profile_picture.blob.content_type.in?(%w[image/jpeg image/jpg image/png])
          errors.add(:profile_picture, 'must be in JPEG, JPG, or PNG format')
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy, :delete_profile_picture]

    def index
        @users = User.all.order(created_at: :desc)
    end

    def show
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            redirect_to user_url(@user)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @user.update(user_params)
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user.destroy

        redirect_to root_path, status: :see_other
    end

    def delete_profile_picture
        if @user.profile_picture.purge
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private
      def find_user
        @user = User.find(params[:id] || params[:user_id])
      end

      def user_params
        params.require(:user).permit(:first_name, :last_name, :profile_picture)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStorageFileUpload</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<div class="form-container">
  <%= form_with model: user do |form| %>
    <div class="form-group">
      <%= form.label :first_name, class: "required-field" %>
      <%= form.text_field :first_name, value: user.first_name %>
      <% user.errors.full_messages_for(:first_name).each do |message| %>
        <div class="danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :last_name, class: "required-field" %>
      <%= form.text_field :last_name, value: user.last_name %>
      <% user.errors.full_messages_for(:last_name).each do |message| %>
        <div class="danger"><%= message %></div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :file_upload %>
      <% if user.profile_picture.attached? && user.profile_picture.image? %>
        <div class="image-preview">
          <%= image_tag(user.profile_picture, width: 80) %>
          <%= link_to user_delete_profile_picture_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "trash-icon" do %>
            <i class="fas fa-trash" title="Delete Image"></i>
          <% end %>
        </div><br><br>
      <% end %>
      <%= form.file_field :profile_picture, accept: 'image/jpeg, image/jpg, image/png' %>
      <% user.errors.full_messages_for(:profile_picture).each do |message| %>
        <div class="danger"><%= message %></div>
      <% end %>
    </div>
  
    <div class="form-group">
      <%= form.submit "Submit", class: "submit-button" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users List</h1>
<%= link_to "Create User", new_user_path, class: "btn btn-primary" %><br><br>
<table class="users-table">
  <thead>
    <tr>
      <!-- <th>S.No<th> -->
      <th>First Name</th>
      <th>Last Name</th>
      <th>Profile</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <!-- <% counter = 1 %> -->
    <% if @users.present? %>
    <% @users.each do |user| %>
      <tr>
        <!-- <td><%= counter %></td> -->
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <% if user.profile_picture.attached? %>
          <td><%= image_tag user.profile_picture, class: "profile-picture" %></td>
        <% else %>
          <td><%= image_tag "avatar.png", class: "profile-picture" %></td>
        <% end %>
        <td>
          <%= link_to "View", user_path(user), class: "btn btn-primary" %>
          <%= link_to "Edit", edit_user_path(user), class: "btn btn-primary" %>
          <%= link_to "Delete", user_path(user), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this user?" }, class: "btn btn-danger" %>
        </td>
      </tr>
      <!-- <% counter += 1 %> -->
    <% end %>
    <% else %>
    <tr><td colspan=4>No users found</td></tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<div class="container">
  <h2 class="user-name">Welcome <%= @user.first_name + " " %><%= @user.last_name %>!</h2>
  <% if @user.profile_picture.attached? %>
    <%= image_tag @user.profile_picture, class: "profile-picture" %>
  <% else %>
    <small><i>No Picture!</i></small>
  <% end %>
</div>